### ISSUE TITLE
User Agent not set

### ISSUE THREAD

**Issue by dotsam** [pfefferle/webfinger-cli#18]
The Net_WebFinger has a bug where the user agent parameter is set incorrectly (`user-agent` instead of `user_agent`), and thus no user-agent string is set.

https://github.com/pear/Net_WebFinger/blob/cf6c397e5cea98f933d8d57243be408d4d47e714/src/Net/WebFinger.php#L456-L465

Some webfinger endpoints (notably [gotosocial](https://github.com/superseriousbusiness/gotosocial) in its default config) will not respond to a request without a user agent header.

I've tried reporting this on the [pear bugtracker](https://pear.php.net/bugs/search.php?cmd=display&package_name[]=Net_WebFinger&status=Open) for the project, but I'm not getting the confirmation email, so I don't know if it will go through.

(I'll somewhat rudely ping @cweiske here to see if they are able to fix this bug and cut a new release)

**Comment by cweiske** [comment]
Fixed in Net_Webfinger 0.4.1

**Comment by dotsam** [comment]
Thanks for the fix @cweiske and thanks for the quick dep update @pfefferle!

Tested and confirmed working against a GoToSocial instance.
